#Now you can display titles to players!
#Simply change the times that fit you.
#Remebmer! - 20 tickes = 1 second. (The numbers are ticks).

###### Title Settings ######
#This settings are for every title.
fadein: 30
stay: 100
fadeout: 100

#clear chat config
Prefix: '&6[&1D&fC&6]&c'
CMessage: '&r'
Message: '&7has cleaned the chat!'
Lines: 150

##### PlaceHolders && Permissions && Icons && Commands ######

  #[%player%] - Player name
  #/ctc - clears full server chat - decp.ctc.clear
  #/ctc lines - shows how many lines of text it will clear - decp.ctc.lines
  #/ctc personal - clears your own chat - decp.ctc.personal
  #/decp reload - Reloads config - decp.reload
  #/website - shows website - no perm
  #/message - can show messages set in config - no perm
  #/Discord - shows discord - no prem
  #/ip shows server ip set in config - no perm
  #/playerip <playername> - shows player ip gamemode health etc - playerip.use
  #/vote - shows vote link - no perm
  #/store shows your store link - no perm
  #/twitch - shows twitch link - no perm
  #/links - put extra links here - no perms
  #/setgui - gui setup menu - decp.gui
  #/youtube - youtube link - no perm


#Icons:
#{icon1} - ❤
#{icon2} - ♕
#{icon3} - ヽ(•‿•)ノ
#{icon4} - ＼(｀0´)／
#{icon5} - ヽ(^o^)ノ
#################
Thank-you-message: true #This is the "Thank you for using DCEasyCmds Prem message" (Only server Opped players see this!)
Command Block:
  Enabled: true
  Commands:
    - "/?"
    - "/bukkit:"
    - "/pl"
    - "/plugins"
    - "/minecraft"
    - "/op"
  Message: "&cYou can not use that command!"
#Discord Section
Discord:
  Enabled: true
  Message:
    - "&7&m----------"
    - "&1D&fC&2N &dDiscord:"
    - "&bhttps://discord.gg/VMx9JmY"
    - "&7&m----------"
  Titles:
    maintitle: "&dDiscord"
    subtitle: "&bhttps://discord.gg/VMx9JmY"

#Website Section
Website:
  Enabled: true
  Message:
    - "&7&m----------"
    - "&1D&fC&2N &8Website:"
    - "&bhttp://doragoncraftnetwork.com/"
    - "&7&m----------"
  Titles:
    maintitle: "&fWebsite"
    subtitle: "&bhttp://doragoncraftnetwork.com/"

#vote section
Vote:
  Enabled: true
  Message:
    - "&7&m----------"
    - "&1D&fC&2N &8Vote:"
    - "&bhttp://doragoncraftnetwork.com/vote"
    - "&7&m----------"
  Titles:
    maintitle: "&fVote"
    subtitle: "&bhttp://doragoncraftnetwork.com/vote"

#Store Section
Store:
  Enabled: true
  Message:
    - "&7&m----------"
    - "&1D&fC&2N &cstore:"
    - "&2http://store.doragoncraftnetwork.com/"
    - "&7&m----------"
  Titles:
    maintitle: "&cStore"
    subtitle: "&bhttp://store.doragoncraftnetwork.com/"

#YouTube Section
Youtube:
  Enabled: true
  Message:
    - "&7&m----------"
    - "&1D&fC&2N  Youtube:"
    - "&bhttps://www.youtube.com/c/doragoncraft"
    - "&7&m----------"
  Titles:
    maintitle: "&fYou&4Tube"
    subtitle: "&bhttps://www.youtube.com/c/doragoncraft"

#Links Section
Links:
  Enabled: true
  Message:
    - "&7&m----------"
    - "&1D&fC&2N  Links"
    - "&bHere!"
    - "&7&m----------"
  Titles:
    maintitle: "&cExtra Links"
    subtitle: "&bTitle2 "

#Twitch Section
Twitch:
  Enabled: true
  Message:
    - "&r"
    - "&1D&fC&2N  Twitch"
    - "&5http://www.twitch.tv/doragoncraft"
  Titles:
    maintitle: "&cTwitch"
    subtitle: "&bhttp://www.twitch.tv/doragoncraft"
#################################

ServerIP Enabled: true
ServerIP:
  - '&7------------------'
  - '&aHey %player%!'
  - '&1D&fC&2N  server IP IS - play.doragoncraftnetwork.com!'
  - '&7------------------'
STitle: "Join now!"
SSubTitle: "Click the link! &b{icon4}"
#################
#Reload Command
Reload-Command: "Config reloaded."

Messages:
  message:
    '1': '&6<======&b&l Messages &6======>'
    '2': '&4thank you for purchasing'
    '3': '&2DCEasyCmds Prem'
    '4': '&cPlease rate &6⭐⭐⭐⭐⭐'
    '5': '&dmy other resources '
    '6': '&6https://www.spigotmc.org/resources/authors/doragoncraft.126499/'
    '7': '&eThank you much love'
    '8': '&6<==================>'

#Feel free to edit the gui.
gui:
  title: "&1D&fE&cC&dP &cControl GUI" #GUI title
  size: 18 #Max size is 27!
  inventory:
    item1: #Do not touch
      slot: 0
      material: BOOK #If the material doesn't exist it will cause an error!
      amount: 1 #Max 64
      data: 0
      item:
        displayname: "&8[&9Discord&8] &fTitle"
        lore:
          - "&7Click Here to edit"
          - "&7Discord main title"
      message-send:
        - "Discord Edit Mode on"
    item2:
      slot: 9
      material: PAPER
      amount: 1
      data: 0
      item:
        displayname: "&8[&9Discord&8] &fSub-Title"
        lore:
          - "&7Click Here to edit"
          - "&7Discord sub title"
      message-send:
        - "Discord Edit Mode on"
    item3:
      slot: 1
      material: BOOK
      amount: 1
      data: 0
      item:
        displayname: "&8[&bWebsite&8] &fTitle"
        lore:
          - "&7Click Here to edit"
          - "&7Website title"
      message-send:
        - "Website Edit Mode on"
    item4:
      slot: 10
      material: PAPER
      amount: 1
      data: 0
      item:
        displayname: "&8[&bWebsite&8] &fSub-Title"
        lore:
          - "&7Click Here to edit"
          - "&7Website sub title"
      message-send:
        - "Website Edit Mode on"
    item5:
      slot: 2
      material: BOOK
      amount: 1
      data: 0
      item:
        displayname: "&8[&cStore&8] &fTitle"
        lore:
          - "&7Click Here to edit"
          - "&7Store title"
      message-send:
        - "Store Edit Mode on"
    item6:
      slot: 11
      material: PAPER
      amount: 1
      data: 0
      item:
        displayname: "&8[&cStore&8] &fSub-Title"
        lore:
          - "&7Click Here to edit"
          - "&7Store Sub title"
      message-send:
        - "Store Edit Mode on"
    item7:
      slot: 3
      material: BOOK
      amount: 1
      data: 0
      item:
        displayname: "&8[&cVote&8] &fTitle"
        lore:
          - "&7Click Here to edit"
          - "&7Vote title"
      message-send:
        - "Store Edit Mode on"
    item8:
      slot: 12
      material: PAPER
      amount: 1
      data: 0
      item:
        displayname: "&8[&cVote&8] &fSub-Title"
        lore:
          - "&7Click Here to edit"
          - "&7Vote Sub title"
      message-send:
        - "Vote Edit Mode on"
    barrier:
      slot: 8
      material: BARRIER
      amount: 1
      data: 0
      item:
        displayname: "&8[&6 Click here to exit edit mode&8 ]"
        lore:
          - "&7Click Here to exit"
      message-send:
        - "You are no longer in edit mode!"
#####################
